### ISSUE TITLE
No access code => code crash

### ISSUE THREAD

**Issue by posikifi** [GispoCoding/NLSgpkgloader#1]
If I don't have access code and press cancel: plugin crashes with following error message:

```
xml.etree.ElementTree.ParseError: syntax error: line 8, column 0 
Traceback (most recent call last):
  File "/home/pos/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NLSgpkgloader-master/nls_geopackage_loader.py", line 233, in run
    self.product_types = self.downloadNLSProductTypes()
  File "/home/pos/.local/share/QGIS/QGIS3/profiles/default/python/plugins/NLSgpkgloader-master/nls_geopackage_loader.py", line 572, in downloadNLSProductTypes
    e = xml.etree.ElementTree.fromstring(r.text)
  File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1333, in XML
    parser.feed(text)
  File "", line None
xml.etree.ElementTree.ParseError: syntax error: line 8, column 0
```

**Comment by SannaJokela** [comment]
Thank you! This will be checked and fixed.
