### ISSUE TITLE
install of plugin on 3.10.12-a as well in 3.12.10 fails

### ISSUE THREAD

**Issue by hannesaddec** [GispoCoding/NLSgpkgloader#27]
Hi, 

against QGIS 75c848ffb1 the installation of the plugin fails - not really sure why as other plugins deploy. 

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
AttributeError: module 'NLSgpkgloader-master' has no attribute 'classFactory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\pyplugin_installer\installer.py", line 636, in installFromZipFile
    if startPlugin(pluginName):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 354, in startPlugin
    if not _startPlugin(packageName):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 336, in _startPlugin
    _unloadPluginModules(packageName)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 448, in _unloadPluginModules
    mods = _plugin_modules[packageName]
KeyError: 'NLSgpkgloader-master'

Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.10.12-A Coruña 'A Coruña', 75c848ffb1

**Comment by SannaJokela** [comment]
This propably has been fixed since there has not been any problems with the latest QGIS versions. Tested today with QGIS 3.34 and Windows and installation from plugin repository works fine. If this occurs, please let us know.
