### ISSUE TITLE
Error when i try to use the plugin

### ISSUE THREAD

**Issue by joonaris** [GispoCoding/NLSgpkgloader#30]
Following error appears when i try to run NLSgpkloader -plugin:

2023-05-04T11:06:42     WARNING    Traceback (most recent call last):
              File "C:\Users/joona/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NLSgpkgloader-master\nls_geopackage_loader.py", line 232, in run
              self.product_types = self.downloadNLSProductTypes()
              File "C:\Users/joona/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NLSgpkgloader-master\nls_geopackage_loader.py", line 571, in downloadNLSProductTypes
              e = xml.etree.ElementTree.fromstring(r.text)
              File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\xml\etree\ElementTree.py", line 1347, in XML
              parser.feed(text)
             xml.etree.ElementTree.ParseError: syntax error: line 8, column 0

**Comment by mvaaltola** [comment]
Duplicate of #20 :slightly_smiling_face:

**Comment by joonaris** [comment]
Niinpäs olikin 😄  ja nyt alkoi toimimaan kun sain oikeat tunnukset.
